services:
  wppconnect:
    image: wppconnect-team/wppconnect-server:latest
    container_name: wppconnect-server
    restart: always
    ports:
      - '3131:21465'   # API
      - '3132:3000'    # Painel
    environment:
      PORT: 21465
      DEBUG: 'true'
      MAX_ATTACHMENT_SIZE: 20
      TOKEN_SECRET: minhasecretkeysegura
      JWT_SECRET: minhajwtsegura
      DATABASE_URL: file:./db.sqlite
      CREATE_ADMIN: 'true'
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
    volumes:
      - ./data:/app/data
